version: "3"

services:

  mysqldb:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: teste_burh
      MYSQL_PORT: '3306'
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    networks:
      - app-network
  
  redis:
    image: redis:7.0-alpine3.17
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
